### ISSUE TITLE
DynamicBridge does not apply Glamourer's "Skin Color" Advanced Customization

### ISSUE THREAD

**Issue by Werns** [Limiana/DynamicBridgeStandalone#17] opened 2024-04-24 02:11 UTC
I have a Glamourer design that sets the skin color to blue. When applying it through Glamourer, it works fine. However, when I set up DynamicBridge to apply that same design, it ignores the Skin Color attribute but does apply all of the other Advanced Customization attributes.

Steps to reproduce:
1. Create a design in Glamourer. Under the "Advanced Customizations" accordion, click the checkbox next to Skin Color and choose a very obvious color. Also click the checkbox for any other option and choose a very obvious color.
2. Create a preset in Dynamic Bridge that will apply the Glamourer design created in step 1.
3. Set the preset created in step 2 to static. The skin color does not change, but the other option selected in step 1 does.

**Comment by Limiana** [comment] 2024-04-27 18:42
Hello! There is an issue in Glamourer that prevents it working. I've already reported it, once it's fixed it should be good

**Comment by Limiana** [comment] 2024-04-27 18:43
I will close this bugreport now as the issue is tracked in another one https://github.com/Limiana/DynamicBridgeStandalone/issues/9

**Closed by Limiana** 2024-04-27 18:43 UTC
Labels: External bug
